travis:
  secure:
    BINSTAR_TOKEN: EEmNqGNCjMQGU+MXYEkjD+f36Qcjacoo5zO0VRvEmw/zWcdOGT7Efv28FlcYmMTcguBFYYydnTjneWZYS8VBGu1ZUFuOpkpyLaR60Dw8aSE3xb6LZ4ipHSgudRcwbeP1OcXVvbf5L6a21b8B0OftxFoVsxpm5toweBP1ct7IXQmzGxo9r/xRYzzhyzCHxY7kC/OdBTXrf20Y2pgQXhqJvyAcJ9swhmKlbfnmhm6LifR69l9UMU5JaHFy8dJhptz+N3I6xwU+PekkprFn+23dKp99Gkf7J7M005l1eAS7YejEWJ7ahEaSa/mMmekYhUPrsbrDequ6yD7COXt9E7RksuQxTGdO6VRoM1W7RkfXKUXG4i4fYcd5o2rJIqFXdC5Yv08oztWMAy8Tw4+m2oR9nMi/9e8Y+OZ7Nv9nuKorXZF905zO1oyaqBB71gX4rmr9uDPNgD1ywgRRZVgbtIyRNYz9BUAmuk2Nh9Lsf7B2i1+QkotYJGu/vVBPg2y2yh4hTizkT/iDbWe4Ybm4NlTQ643MjV87IvOSjx0bA+LOOTBtRkYmZXvsBs8VButWHDnCy8j5NTq0iZWfAtQ0GJ7qPEjkNMY70i1tvVvyTvQzdDaw1eH6Xc0FHgp/Dv8GOrgkNT/ELLhHEtJedaSOPkPkZC0TqALLVbrOmM0xVbwbJk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
