travis:
  secure:
    BINSTAR_TOKEN: UAhyXq8M+67V5Qw8rCgqyQySHvoK7bkokjhwcE4PCG5yfvvEdOLbREB9eNUvTsFnYwtPLBfW1iFZ/6eOIs5xaaH+c9mRNWdkTVscifGIKE/bPCgD3jvl8hPMxk/r+u7A3K/EZ0ar6W6DUGdr7DadMqzlg0+40K9MvcWtIshJVax9zbBOBkFLR7PbDpzJe7VQ1qU+zWhRfEqCMJQW7Vw/e5vrqrIXV3mTPGCpKxQKp+NasKgUvwUt4e1vkKXPVVKvuZo8PK+xbWNcPhTdbxSw5VQfuLSW7SAqc9GKLowKxUGUqQe6DTKSLaVoerwzDu/VFAVst0uVlXnLSwHaT3nLhRrx+w1JOI5Gh21o8Jx263wdGZJFNdn3cuo8IjGV10IQgLq2xLvSjj1+iHc5TcdbvJtvhRFlnmHPS3g9fajh84TrEPEx3mhk8GoMgtTpBObhq6ju/dGQMSrDIvuTfzMJoCNTHzKRXSRnc9ve2m7gUg+kMyY+OAWxr7vx6liGxlPurdu/w4zzlB/bv9WMt0q6FjjNRqASqSRblQZmNiyFjwQ+Q7ARAEo7G+zkUQbKfIwQfVjHOkl0lY1cCXo7hN+W3hlmCpcFDD1HQJex0mRHoiyfUzr0pkIekayroqfDPyann9SgPTjfX2uZRB4c3hchtPh7IlTCjROAPNGUzsnJmvA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
