travis:
  secure:
    BINSTAR_TOKEN: GlRkgATbrSFcrQCt7nTMeBM8AsYxcVLr2iUYfQJVaPKGZZJmR2F5ueETV+IScvI4P3cTwp5VFxw6NyiLPX8FDPPTqVyUIp6lravOJM6mWZG5JoeV/qnoPXrrS2vHt2PvZp7OG/O/FDf9VMHTRFvkUiK8xdnwvmAQxnG6htbH2CzHMssSwaeR7mpV11KFt4KZUxywmTuGeYpytyP9IXUL1f6m6FmD1yK7hj3KBNenHOqXssYXvere54P3RoHQ14j/GcTR9JkgWiD7O/sKV8E0nUb+sf95hhu8ybkdTg4yl9Yn8/K2Dzu4QiuCoCJA+ftmpPm5HDoAF9cMTYLEVaGURMA3dEs8zjgQH37qtS+R6R75DJ0mQNCXk+L4e0FVBc1L02quGqxiwiz+x8Pczx3hvBlkUIQHm6eWOibWyacam55pzNAl55fet4b9GCqqZr5lJJ40JyHijjOimFFJRyTDGUPkq9WS33a71GJ5VkQe5nrBfnv614aY2QsyWh+geypxaKpSqBh1Z4EwA6v+SvdhjuQffSFymF81zYMEnFscfdw4acTNUXZOraK/1bzFb2zELXD7iz3FCCBJEx2ofXxurzUw9lliflEF+al6+qfbmi5+K7OxPK5zeGL836tAl5+81bz23gsEJGadID4X7Hgo9s1BnLGW7blG8LkbtPPHyag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
