travis:
  secure:
    BINSTAR_TOKEN: AKgzR4ocuzFYbwW2m4SBy8Y2TTQkFyIBzxLLqY5P+SfYCpty+vOQAeuqqLC600MvV8pKwWgm499xEf/oAecAyR/5zlr9/tWR+V8TEngDnlqfhm9ghUt8rl0YiQzTReackOvhF11K5mvxJKTf4BDJTRrbNhyjayaZrpMjWHi+oEwWVl9znX0RJulDtKOOAuP+5cSDu6rufx4TAsi0aaOSV2Fj9Dd3A4ZNxXYJMzn9zdi4f8EMNkkGyDD2jdnGLnK8S+P/XTdRGHTfXHRYDssP3hfRPTxduCFdIfaZRcDAvIEswKwnNKzAy1FWZKXN9kup0siTPGb4m5vn4UARmwVPBm5SAxmUHmLQNB1r9kIzD5jhU1d2eyr7n3OqranZyiYlerkDtKwv3ZC4agQ8kg0tj5d0v9D9qdtU0R/lOPZXl9/CyMoIA427odBF/IuyeQy58IaDhgVxKw1wfueuUrc2cf2Pyzs4fOVQmNiplWA6C9iNtg5ro78M9BYCLRYpHuty//mFeDlSdiC+SqjyP4/Ggc89JVzaUhQsFr+VyTuBtZcxFzP7OvvWTxvPUqGhfehDfObZNVo+9OljnNVRz+Xy3ysbcRb28yF0rk5WvIO/UkJmg3In+sS2Iw+UGY+mgCoAE5mUFPB3daQ6guAmS/cDmHycFkJ3NejwOloZQRqfUcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
